language: php
php:
- 5.6
- 5.5
install:
- composer install
scripts:
  - mkdir -p build/logs
env:
  global:
  - APP_ENV=testing
  - TWILIO_AUTH_TOKEN=token_here
  - TWILIO_ACCOUNT_SID=sid_here
  - TWILIO_NUMBER=number_here
